name: 'Build & Check: Ubuntu Full QT & Tests'

on:
  push:
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Basic Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config python3 \
          libssl-dev bsdmainutils libevent-dev \
          libboost-dev libboost-system-dev libboost-filesystem-dev libboost-test-dev \
          libsqlite3-dev \
          libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools \
          libqrencode-dev

      - name: Install pypandoc
        run: pip3 install pypandoc

      - name: Install scrypt for Python3
        run: pip3 install digibyte_scrypt
      
      - name: Install BerkleyDB
        run: ./contrib/install_db4.sh `pwd` --enable-cxx

      - name: Build Dependencies
        run: |
          cd depends
          make -j3 HOST=x86_64-linux-gnu
          cd ..

      - name: Auto Generate
        run: ./autogen.sh

      - name: Configure
        run: CONFIG_SITE=$PWD/depends/x86_64-linux-gnu/share/config.site ./configure --with-bdb --with-sqlite --with-gui=yes

      - name: Make
        run: make -j3

      - name: Make Check
        run: make check -j3

      - name: Upload Test Suite Log
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-suite-log
          path: /src/test-suite.log